CI: Add coverage job

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -29,11 +29,15 @@ stages:
     DOCKER_HOST: tcp://docker:2375
     DOCKER_TLS_CERTDIR: ""
   script:
-    - go test -coverprofile=coverage.out -coverpkg=./auth/...,./lib/...,./model/...,./validation/... ./tests/...
-    - apt-get update && apt-get install -y bc
-    - COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
-    - echo "Total coverage: $COVERAGE%"
-    - 'if (( $(echo "$COVERAGE < 80.0" | bc -l) )); then echo "Error: Code coverage is below 80%."; exit 1; fi'
+    - |
+      go test -coverprofile=coverage.out -coverpkg=./auth/...,./lib/...,./model/...,./validation/... ./tests/...
+      apt-get update && apt-get install -y bc
+      COVERAGE=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | sed 's/%//')
+      echo "Total coverage: $COVERAGE%"
+      if (( $(echo "$COVERAGE < 80.0" | bc -l) )); then
+        echo "Error: Code coverage is below 80%."
+        exit 1
+      fi
   cache:
     key:
       files:
